### ISSUE TITLE
Update the password reset screen and email

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#234]
- Title: Forgot your password? Need to reset it?
- Enter your email address and we will send you a new password.
- A message has been sent to your email address with a new password. If it doesn’t appear within a few minutes, check your spam folder.

**Current**
![image](https://user-images.githubusercontent.com/14092820/67488134-926e0f80-f66f-11e9-9b80-0615e70207fc.png)

**Final:** 
![image](https://user-images.githubusercontent.com/14092820/67488088-71a5ba00-f66f-11e9-977e-c91e07f959eb.png)

**Email text:**
Dear first name + last name,

We received a request to reset the password for your AgroFIMS account. 

Please use the following password to log in to your account:  
XXXXXXXXXX

Best,
The AgroFIMS (insert link: https://apps.cipotato.org/hidapagrofims/) Team

**Comment by omarbenites** [comment]
Fixed for the next update ✅

**Comment by celineaubert** [comment]
Hi @omarbenites 
Thanks for the update. I noticed a typo in '' address''. Also the title has not been changed
![image](https://user-images.githubusercontent.com/14092820/70040759-57d78b00-15bc-11ea-8223-36e6e76353bf.png)


- [ ] the word ''address'' is missing in the confirmation message. 
![image](https://user-images.githubusercontent.com/14092820/70041147-e815d000-15bc-11ea-9c47-ebeca7e6bf2c.png)

- [ ] It is very long to receive the new password (6 hours). Is it possible to reduce the time?

**Comment by celineaubert** [comment]
Some changes are missing in the last version

**Comment by celineaubert** [comment]
Some changes are still missing:

- [ ] Remove HiDAP from the email message title

- [ ] Add AgroFIMS logo - if possible a clickable logo with the link to AgroFIMS website.

![image](https://user-images.githubusercontent.com/14092820/74238162-81f0ac00-4cd5-11ea-9972-b4ea0cef18f2.png)
